server.port: 8080
logging.level.com.github.xiaoymin.knife4j.aggre.repository: debug
knife4j:
  enable-aggregation: true
  cloud:
    enable: true
    routes:
      - name: platform
        uri: http://127.0.0.1:20001/api/platform
        location: /v3/api-docs
      - name: enterprise
        uri: http://127.0.0.1:10001/api/enterprise
        location: /v3/api-docs